/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Shallowfind
 * Lifetime financial planning API
 * OpenAPI spec version: 0.0.1a
 */
import { z as zod } from 'zod';

/**
 * Handles the OAuth callback and exchanges code for tokens
 * @summary Google Callback
 */
export const googleCallbackAuthGoogleCallbackGetQueryParams = zod.object({
  code: zod.string().or(zod.null()).optional()
});

export const googleCallbackAuthGoogleCallbackGetResponse = zod.any();

/**
 * @summary Google Login
 */
export const googleLoginAuthGoogleLoginGetResponse = zod.any();

/**
 * Create a guest session and set JWT cookie
 * @summary Create Guest Session
 */
export const createGuestSessionAuthGuestLoginPostResponseIsGuestDefault = true;

export const createGuestSessionAuthGuestLoginPostResponse = zod.object({
  access_token: zod.string(),
  is_guest: zod.boolean().default(createGuestSessionAuthGuestLoginPostResponseIsGuestDefault),
  token_type: zod.string(),
  user: zod.null().optional()
});
