components:
  schemas:
    GuestLoginResponse:
      properties:
        access_token:
          title: Access Token
          type: string
        is_guest:
          default: true
          title: Is Guest
          type: boolean
        token_type:
          title: Token Type
          type: string
        user:
          title: User
          type: 'null'
      required:
      - access_token
      - token_type
      title: GuestLoginResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    UserProfileResponse:
      properties:
        created_at:
          title: Created At
          type: string
        email:
          anyOf:
          - type: string
          - type: 'null'
          title: Email
        google_id:
          anyOf:
          - type: string
          - type: 'null'
          title: Google Id
        id:
          title: Id
          type: string
        last_login:
          anyOf:
          - type: string
          - type: 'null'
          title: Last Login
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
      required:
      - id
      - email
      - name
      - google_id
      - created_at
      - last_login
      title: UserProfileResponse
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: Lifetime financial planning API
  title: Shallowfind
  version: 0.0.1a
openapi: 3.1.0
paths:
  /:
    get:
      operationId: read_root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Read Root
  /api/users/{user_id}:
    get:
      description: Fetch user by ID
      operationId: get_user_api_users__user_id__get
      parameters:
      - in: path
        name: user_id
        required: true
        schema:
          title: User Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get User
      tags:
      - Users
  /auth/google/callback:
    get:
      description: Handles the OAuth callback and exchanges code for tokens
      operationId: google_callback_auth_google_callback_get
      parameters:
      - in: query
        name: code
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Code
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Google Callback
      tags:
      - Authentication
  /auth/google/login:
    get:
      operationId: google_login_auth_google_login_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Google Login
      tags:
      - Authentication
  /auth/guest/login:
    post:
      description: Create a guest session and set JWT cookie
      operationId: create_guest_session_auth_guest_login_post
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuestLoginResponse'
          description: Successful Response
      summary: Create Guest Session
      tags:
      - Authentication
  /health:
    get:
      operationId: health_check_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Health Check
