# Generated by Django 5.2.1 on 2025-05-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("glide_path", "Glide Path")],
                        default="fixed",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="eventseries",
            name="asset_allocation_end",
        ),
        migrations.RemoveField(
            model_name="eventseries",
            name="glide_path",
        ),
        migrations.AlterField(
            model_name="eventseries",
            name="asset_allocation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_series",
                to="scenarios.assetallocation",
            ),
        ),
        migrations.CreateModel(
            name="InvestmentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.FloatField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Allocation"),
                            ("final", "Final Allocation (for glide-path)"),
                        ],
                        default="primary",
                        max_length=8,
                    ),
                ),
                (
                    "asset_allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_allocations",
                        to="scenarios.assetallocation",
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="scenarios.investment",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset_allocation", "investment", "role")},
            },
        ),
    ]
