# Generated by Django 5.2.1 on 2025-07-07 23:58

import scenarios.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="eventseries",
            name="change_distribution",
            field=scenarios.models.DistributionField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="eventseries",
            name="start_distribution",
            field=scenarios.models.DistributionField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="spouse_life_expectancy",
            field=scenarios.models.DistributionField(
                blank=True, default=None, null=True
            ),
        ),
    ]
