# Generated by Django 5.2.1 on 2025-07-09 04:38

import django.core.validators
import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0002_scenario_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="value",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="after_tax_contribution_limit",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="USD",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="financial_goal",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="USD",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
