# Generated by Django 5.2.1 on 2025-06-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenarios", "0003_alter_scenario_residence_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="marital_status",
            field=models.CharField(
                choices=[("individual", "Individual"), ("couple", "Couple")],
                default="individual",
                max_length=10,
            ),
        ),
    ]
