/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Scenario Manager API
 * API for managing scenarios, strategies, and investments.
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreateScenarioRequest,
  ScenarioResponse,
  UpdateScenarioRequest
} from '../scenarioManagerAPI.schemas';

export const getScenarios = () => {
  const postApiScenarios = <TData = AxiosResponse<ScenarioResponse>>(
    createScenarioRequest: CreateScenarioRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(`http://localhost:5050/api/scenarios`, createScenarioRequest, options);
  };
  const getApiScenarios = <TData = AxiosResponse<ScenarioResponse[]>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`http://localhost:5050/api/scenarios`, options);
  };
  const getApiScenariosId = <TData = AxiosResponse<ScenarioResponse>>(
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`http://localhost:5050/api/scenarios/${id}`, options);
  };
  const putApiScenariosId = <TData = AxiosResponse<ScenarioResponse>>(
    id: string,
    updateScenarioRequest: UpdateScenarioRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.put(`http://localhost:5050/api/scenarios/${id}`, updateScenarioRequest, options);
  };
  const deleteApiScenariosId = <TData = AxiosResponse<null>>(
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.delete(`http://localhost:5050/api/scenarios/${id}`, options).then((res) => {
      if (res.data === '') res.data = null;
      return res as TData;
    });
  };
  return {
    postApiScenarios,
    getApiScenarios,
    getApiScenariosId,
    putApiScenariosId,
    deleteApiScenariosId
  };
};
export type PostApiScenariosResult = AxiosResponse<ScenarioResponse>;
export type GetApiScenariosResult = AxiosResponse<ScenarioResponse[]>;
export type GetApiScenariosIdResult = AxiosResponse<ScenarioResponse>;
export type PutApiScenariosIdResult = AxiosResponse<ScenarioResponse>;
export type DeleteApiScenariosIdResult = AxiosResponse<null>;
