/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Shallowfind
 * Lifetime financial planning API
 * OpenAPI spec version: 0.0.1a
 */
export interface GuestLoginResponse {
  access_token: string;
  is_guest?: boolean;
  token_type: string;
  user?: null;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type UserProfileResponseEmail = string | null;

export type UserProfileResponseGoogleId = string | null;

export type UserProfileResponseLastLogin = string | null;

export type UserProfileResponseName = string | null;

export interface UserProfileResponse {
  created_at: string;
  email: UserProfileResponseEmail;
  google_id: UserProfileResponseGoogleId;
  id: string;
  last_login: UserProfileResponseLastLogin;
  name: UserProfileResponseName;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GoogleCallbackAuthGoogleCallbackGetParams = {
  code?: string | null;
};
