/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ScenarioManager.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import { createMutation, createQuery } from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreateIncomeEventRequest,
  EventSeriesResponse
} from '../scenarioManagerApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

export const postApiScenariosScenarioIdIncomeEvents = (
  scenarioId: string,
  createIncomeEventRequest: CreateIncomeEventRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse>> => {
  return axios.post(
    `/api/scenarios/${scenarioId}/income-events`,
    createIncomeEventRequest,
    options
  );
};

export const getPostApiScenariosScenarioIdIncomeEventsMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof postApiScenariosScenarioIdIncomeEvents>>,
    TError,
    { scenarioId: string; data: CreateIncomeEventRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdIncomeEvents>>,
  TError,
  { scenarioId: string; data: CreateIncomeEventRequest },
  TContext
> => {
  const mutationKey = ['postApiScenariosScenarioIdIncomeEvents'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiScenariosScenarioIdIncomeEvents>>,
    { scenarioId: string; data: CreateIncomeEventRequest }
  > = (props) => {
    const { scenarioId, data } = props ?? {};

    return postApiScenariosScenarioIdIncomeEvents(scenarioId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiScenariosScenarioIdIncomeEventsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdIncomeEvents>>
>;
export type PostApiScenariosScenarioIdIncomeEventsMutationBody = CreateIncomeEventRequest;
export type PostApiScenariosScenarioIdIncomeEventsMutationError = AxiosError<unknown>;

export const createPostApiScenariosScenarioIdIncomeEvents = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof postApiScenariosScenarioIdIncomeEvents>>,
      TError,
      { scenarioId: string; data: CreateIncomeEventRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdIncomeEvents>>,
  TError,
  { scenarioId: string; data: CreateIncomeEventRequest },
  TContext
> => {
  const mutationOptions = getPostApiScenariosScenarioIdIncomeEventsMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
export const getApiScenariosScenarioIdIncomeEvents = (
  scenarioId: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse[]>> => {
  return axios.get(`/api/scenarios/${scenarioId}/income-events`, options);
};

export const getGetApiScenariosScenarioIdIncomeEventsQueryKey = (scenarioId?: string) => {
  return [`/api/scenarios/${scenarioId}/income-events`] as const;
};

export const getGetApiScenariosScenarioIdIncomeEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEvents>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEvents>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiScenariosScenarioIdIncomeEventsQueryKey(scenarioId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEvents>>
  > = ({ signal }) =>
    getApiScenariosScenarioIdIncomeEvents(scenarioId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!scenarioId,
    useQuery: true,
    staleTime: 300000,
    ...queryOptions
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiScenariosScenarioIdIncomeEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEvents>>
>;
export type GetApiScenariosScenarioIdIncomeEventsQueryError = AxiosError<unknown>;

export function createGetApiScenariosScenarioIdIncomeEvents<
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEvents>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEvents>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiScenariosScenarioIdIncomeEventsQueryOptions(scenarioId, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiScenariosScenarioIdIncomeEventsId = (
  scenarioId: string,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse>> => {
  return axios.get(`/api/scenarios/${scenarioId}/income-events/${id}`, options);
};

export const getGetApiScenariosScenarioIdIncomeEventsIdQueryKey = (
  scenarioId?: string,
  id?: string
) => {
  return [`/api/scenarios/${scenarioId}/income-events/${id}`] as const;
};

export const getGetApiScenariosScenarioIdIncomeEventsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEventsId>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  id: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEventsId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiScenariosScenarioIdIncomeEventsIdQueryKey(scenarioId, id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEventsId>>
  > = ({ signal }) =>
    getApiScenariosScenarioIdIncomeEventsId(scenarioId, id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(scenarioId && id),
    useQuery: true,
    staleTime: 300000,
    ...queryOptions
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEventsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiScenariosScenarioIdIncomeEventsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEventsId>>
>;
export type GetApiScenariosScenarioIdIncomeEventsIdQueryError = AxiosError<unknown>;

export function createGetApiScenariosScenarioIdIncomeEventsId<
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEventsId>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  id: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdIncomeEventsId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiScenariosScenarioIdIncomeEventsIdQueryOptions(
    scenarioId,
    id,
    options
  );

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiScenariosScenarioIdIncomeEventsId = (
  scenarioId: string,
  id: string,
  createIncomeEventRequest: CreateIncomeEventRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse>> => {
  return axios.put(
    `/api/scenarios/${scenarioId}/income-events/${id}`,
    createIncomeEventRequest,
    options
  );
};

export const getPutApiScenariosScenarioIdIncomeEventsIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof putApiScenariosScenarioIdIncomeEventsId>>,
    TError,
    { scenarioId: string; id: string; data: CreateIncomeEventRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdIncomeEventsId>>,
  TError,
  { scenarioId: string; id: string; data: CreateIncomeEventRequest },
  TContext
> => {
  const mutationKey = ['putApiScenariosScenarioIdIncomeEventsId'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiScenariosScenarioIdIncomeEventsId>>,
    { scenarioId: string; id: string; data: CreateIncomeEventRequest }
  > = (props) => {
    const { scenarioId, id, data } = props ?? {};

    return putApiScenariosScenarioIdIncomeEventsId(scenarioId, id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiScenariosScenarioIdIncomeEventsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdIncomeEventsId>>
>;
export type PutApiScenariosScenarioIdIncomeEventsIdMutationBody = CreateIncomeEventRequest;
export type PutApiScenariosScenarioIdIncomeEventsIdMutationError = AxiosError<unknown>;

export const createPutApiScenariosScenarioIdIncomeEventsId = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof putApiScenariosScenarioIdIncomeEventsId>>,
      TError,
      { scenarioId: string; id: string; data: CreateIncomeEventRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdIncomeEventsId>>,
  TError,
  { scenarioId: string; id: string; data: CreateIncomeEventRequest },
  TContext
> => {
  const mutationOptions = getPutApiScenariosScenarioIdIncomeEventsIdMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
export const deleteApiScenariosScenarioIdIncomeEventsId = (
  scenarioId: string,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<null>> => {
  return axios.delete(`/api/scenarios/${scenarioId}/income-events/${id}`, options);
};

export const getDeleteApiScenariosScenarioIdIncomeEventsIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof deleteApiScenariosScenarioIdIncomeEventsId>>,
    TError,
    { scenarioId: string; id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdIncomeEventsId>>,
  TError,
  { scenarioId: string; id: string },
  TContext
> => {
  const mutationKey = ['deleteApiScenariosScenarioIdIncomeEventsId'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiScenariosScenarioIdIncomeEventsId>>,
    { scenarioId: string; id: string }
  > = (props) => {
    const { scenarioId, id } = props ?? {};

    return deleteApiScenariosScenarioIdIncomeEventsId(scenarioId, id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiScenariosScenarioIdIncomeEventsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdIncomeEventsId>>
>;

export type DeleteApiScenariosScenarioIdIncomeEventsIdMutationError = AxiosError<unknown>;

export const createDeleteApiScenariosScenarioIdIncomeEventsId = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof deleteApiScenariosScenarioIdIncomeEventsId>>,
      TError,
      { scenarioId: string; id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdIncomeEventsId>>,
  TError,
  { scenarioId: string; id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiScenariosScenarioIdIncomeEventsIdMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
