/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Scenario Manager API
 * API for managing scenarios, strategies, and investments.
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { CreateIncomeEventRequest, EventSeriesResponse } from '../scenarioManagerAPI.schemas';

export const getIncomeEvents = () => {
  const postApiScenariosScenarioIdIncomeEvents = <TData = AxiosResponse<EventSeriesResponse>>(
    scenarioId: string,
    createIncomeEventRequest: CreateIncomeEventRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(
      `http://localhost:5050/api/scenarios/${scenarioId}/income-events`,
      createIncomeEventRequest,
      options
    );
  };
  const getApiScenariosScenarioIdIncomeEvents = <TData = AxiosResponse<EventSeriesResponse[]>>(
    scenarioId: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`http://localhost:5050/api/scenarios/${scenarioId}/income-events`, options);
  };
  const getApiScenariosScenarioIdIncomeEventsId = <TData = AxiosResponse<EventSeriesResponse>>(
    scenarioId: string,
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(
      `http://localhost:5050/api/scenarios/${scenarioId}/income-events/${id}`,
      options
    );
  };
  const putApiScenariosScenarioIdIncomeEventsId = <TData = AxiosResponse<EventSeriesResponse>>(
    scenarioId: string,
    id: string,
    createIncomeEventRequest: CreateIncomeEventRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.put(
      `http://localhost:5050/api/scenarios/${scenarioId}/income-events/${id}`,
      createIncomeEventRequest,
      options
    );
  };
  const deleteApiScenariosScenarioIdIncomeEventsId = <TData = AxiosResponse<null>>(
    scenarioId: string,
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios
      .delete(`http://localhost:5050/api/scenarios/${scenarioId}/income-events/${id}`, options)
      .then((res) => {
        if (res.data === '') res.data = null;
        return res as TData;
      });
  };
  return {
    postApiScenariosScenarioIdIncomeEvents,
    getApiScenariosScenarioIdIncomeEvents,
    getApiScenariosScenarioIdIncomeEventsId,
    putApiScenariosScenarioIdIncomeEventsId,
    deleteApiScenariosScenarioIdIncomeEventsId
  };
};
export type PostApiScenariosScenarioIdIncomeEventsResult = AxiosResponse<EventSeriesResponse>;
export type GetApiScenariosScenarioIdIncomeEventsResult = AxiosResponse<EventSeriesResponse[]>;
export type GetApiScenariosScenarioIdIncomeEventsIdResult = AxiosResponse<EventSeriesResponse>;
export type PutApiScenariosScenarioIdIncomeEventsIdResult = AxiosResponse<EventSeriesResponse>;
export type DeleteApiScenariosScenarioIdIncomeEventsIdResult = AxiosResponse<null>;
