/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Shallowfind
 * Lifetime financial planning API
 * OpenAPI spec version: 0.0.1a
 */
import { z as zod } from 'zod';

/**
 * @summary Read Root
 */
export const readRootGetResponse = zod.any();

/**
 * @summary Health Check
 */
export const healthCheckHealthGetResponse = zod.any();
