/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ScenarioManager.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import { createMutation, createQuery } from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreateExpenseEventRequest,
  EventSeriesResponse
} from '../scenarioManagerApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

export const postApiScenariosScenarioIdExpenseEvents = (
  scenarioId: string,
  createExpenseEventRequest: CreateExpenseEventRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse>> => {
  return axios.post(
    `/api/scenarios/${scenarioId}/expense-events`,
    createExpenseEventRequest,
    options
  );
};

export const getPostApiScenariosScenarioIdExpenseEventsMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof postApiScenariosScenarioIdExpenseEvents>>,
    TError,
    { scenarioId: string; data: CreateExpenseEventRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdExpenseEvents>>,
  TError,
  { scenarioId: string; data: CreateExpenseEventRequest },
  TContext
> => {
  const mutationKey = ['postApiScenariosScenarioIdExpenseEvents'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiScenariosScenarioIdExpenseEvents>>,
    { scenarioId: string; data: CreateExpenseEventRequest }
  > = (props) => {
    const { scenarioId, data } = props ?? {};

    return postApiScenariosScenarioIdExpenseEvents(scenarioId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiScenariosScenarioIdExpenseEventsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdExpenseEvents>>
>;
export type PostApiScenariosScenarioIdExpenseEventsMutationBody = CreateExpenseEventRequest;
export type PostApiScenariosScenarioIdExpenseEventsMutationError = AxiosError<unknown>;

export const createPostApiScenariosScenarioIdExpenseEvents = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof postApiScenariosScenarioIdExpenseEvents>>,
      TError,
      { scenarioId: string; data: CreateExpenseEventRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdExpenseEvents>>,
  TError,
  { scenarioId: string; data: CreateExpenseEventRequest },
  TContext
> => {
  const mutationOptions = getPostApiScenariosScenarioIdExpenseEventsMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
export const getApiScenariosScenarioIdExpenseEvents = (
  scenarioId: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse[]>> => {
  return axios.get(`/api/scenarios/${scenarioId}/expense-events`, options);
};

export const getGetApiScenariosScenarioIdExpenseEventsQueryKey = (scenarioId?: string) => {
  return [`/api/scenarios/${scenarioId}/expense-events`] as const;
};

export const getGetApiScenariosScenarioIdExpenseEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEvents>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEvents>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiScenariosScenarioIdExpenseEventsQueryKey(scenarioId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEvents>>
  > = ({ signal }) =>
    getApiScenariosScenarioIdExpenseEvents(scenarioId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!scenarioId,
    useQuery: true,
    staleTime: 300000,
    ...queryOptions
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiScenariosScenarioIdExpenseEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEvents>>
>;
export type GetApiScenariosScenarioIdExpenseEventsQueryError = AxiosError<unknown>;

export function createGetApiScenariosScenarioIdExpenseEvents<
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEvents>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEvents>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiScenariosScenarioIdExpenseEventsQueryOptions(scenarioId, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiScenariosScenarioIdExpenseEventsId = (
  scenarioId: string,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse>> => {
  return axios.get(`/api/scenarios/${scenarioId}/expense-events/${id}`, options);
};

export const getGetApiScenariosScenarioIdExpenseEventsIdQueryKey = (
  scenarioId?: string,
  id?: string
) => {
  return [`/api/scenarios/${scenarioId}/expense-events/${id}`] as const;
};

export const getGetApiScenariosScenarioIdExpenseEventsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEventsId>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  id: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEventsId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiScenariosScenarioIdExpenseEventsIdQueryKey(scenarioId, id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEventsId>>
  > = ({ signal }) =>
    getApiScenariosScenarioIdExpenseEventsId(scenarioId, id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(scenarioId && id),
    useQuery: true,
    staleTime: 300000,
    ...queryOptions
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEventsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiScenariosScenarioIdExpenseEventsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEventsId>>
>;
export type GetApiScenariosScenarioIdExpenseEventsIdQueryError = AxiosError<unknown>;

export function createGetApiScenariosScenarioIdExpenseEventsId<
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEventsId>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  id: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdExpenseEventsId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiScenariosScenarioIdExpenseEventsIdQueryOptions(
    scenarioId,
    id,
    options
  );

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiScenariosScenarioIdExpenseEventsId = (
  scenarioId: string,
  id: string,
  createExpenseEventRequest: CreateExpenseEventRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<EventSeriesResponse>> => {
  return axios.put(
    `/api/scenarios/${scenarioId}/expense-events/${id}`,
    createExpenseEventRequest,
    options
  );
};

export const getPutApiScenariosScenarioIdExpenseEventsIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof putApiScenariosScenarioIdExpenseEventsId>>,
    TError,
    { scenarioId: string; id: string; data: CreateExpenseEventRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdExpenseEventsId>>,
  TError,
  { scenarioId: string; id: string; data: CreateExpenseEventRequest },
  TContext
> => {
  const mutationKey = ['putApiScenariosScenarioIdExpenseEventsId'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiScenariosScenarioIdExpenseEventsId>>,
    { scenarioId: string; id: string; data: CreateExpenseEventRequest }
  > = (props) => {
    const { scenarioId, id, data } = props ?? {};

    return putApiScenariosScenarioIdExpenseEventsId(scenarioId, id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiScenariosScenarioIdExpenseEventsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdExpenseEventsId>>
>;
export type PutApiScenariosScenarioIdExpenseEventsIdMutationBody = CreateExpenseEventRequest;
export type PutApiScenariosScenarioIdExpenseEventsIdMutationError = AxiosError<unknown>;

export const createPutApiScenariosScenarioIdExpenseEventsId = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof putApiScenariosScenarioIdExpenseEventsId>>,
      TError,
      { scenarioId: string; id: string; data: CreateExpenseEventRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdExpenseEventsId>>,
  TError,
  { scenarioId: string; id: string; data: CreateExpenseEventRequest },
  TContext
> => {
  const mutationOptions = getPutApiScenariosScenarioIdExpenseEventsIdMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
export const deleteApiScenariosScenarioIdExpenseEventsId = (
  scenarioId: string,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<null>> => {
  return axios.delete(`/api/scenarios/${scenarioId}/expense-events/${id}`, options);
};

export const getDeleteApiScenariosScenarioIdExpenseEventsIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof deleteApiScenariosScenarioIdExpenseEventsId>>,
    TError,
    { scenarioId: string; id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdExpenseEventsId>>,
  TError,
  { scenarioId: string; id: string },
  TContext
> => {
  const mutationKey = ['deleteApiScenariosScenarioIdExpenseEventsId'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiScenariosScenarioIdExpenseEventsId>>,
    { scenarioId: string; id: string }
  > = (props) => {
    const { scenarioId, id } = props ?? {};

    return deleteApiScenariosScenarioIdExpenseEventsId(scenarioId, id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiScenariosScenarioIdExpenseEventsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdExpenseEventsId>>
>;

export type DeleteApiScenariosScenarioIdExpenseEventsIdMutationError = AxiosError<unknown>;

export const createDeleteApiScenariosScenarioIdExpenseEventsId = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof deleteApiScenariosScenarioIdExpenseEventsId>>,
      TError,
      { scenarioId: string; id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdExpenseEventsId>>,
  TError,
  { scenarioId: string; id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiScenariosScenarioIdExpenseEventsIdMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
