/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Shallowfind
 * Shallowfind Financial Planner
 * OpenAPI spec version: 0.0.1
 */
import {
  z as zod
} from 'zod';


/**
 * Takes a set of user credentials and returns an access and refresh JSON web
token pair to prove the authentication of those credentials.
 */
export const tokenCreateBody = zod.object({
  "email": zod.string(),
  "password": zod.string()
})

export const tokenCreateResponse = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "access": zod.string(),
  "refresh": zod.string()
})

/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const tokenRefreshCreateBody = zod.object({
  "refresh": zod.string()
})

export const tokenRefreshCreateResponse = zod.object({
  "access": zod.string(),
  "refresh": zod.string()
})

