/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Scenario Manager API
 * API for managing scenarios, strategies, and investments.
 * OpenAPI spec version: v1
 */
import { z as zod } from 'zod';

export const postApiScenariosScenarioIdRebalanceEventsParams = zod.object({
  scenarioId: zod.string()
});

export const postApiScenariosScenarioIdRebalanceEventsBodyNameMax = 255;
export const postApiScenariosScenarioIdRebalanceEventsBodyDescriptionMax = 1000;
export const postApiScenariosScenarioIdRebalanceEventsBodyStartTimingTypeMax = 50;

export const postApiScenariosScenarioIdRebalanceEventsBody = zod.object({
  name: zod.string().min(1).max(postApiScenariosScenarioIdRebalanceEventsBodyNameMax),
  description: zod
    .string()
    .max(postApiScenariosScenarioIdRebalanceEventsBodyDescriptionMax)
    .nullish(),
  startYear: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  duration: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  referenceEventSeriesId: zod.string().nullish(),
  startTimingType: zod
    .string()
    .max(postApiScenariosScenarioIdRebalanceEventsBodyStartTimingTypeMax)
    .nullish(),
  isActive: zod.boolean().optional(),
  orderIndex: zod.number().optional(),
  assetAllocation: zod.record(zod.string(), zod.number()),
  isGlidePath: zod.boolean().optional(),
  initialAllocation: zod.record(zod.string(), zod.number()).nullish(),
  finalAllocation: zod.record(zod.string(), zod.number()).nullish(),
  targetTaxStatus: zod.enum(['NonRetirement', 'PreTaxRetirement', 'AfterTaxRetirement'])
});

export const postApiScenariosScenarioIdRebalanceEventsResponse = zod.object({
  id: zod.string().nullable(),
  scenarioId: zod.string().nullable(),
  name: zod.string().nullable(),
  description: zod.string().nullish(),
  eventType: zod.enum(['Income', 'Expense', 'Invest', 'Rebalance']).optional(),
  startYear: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  duration: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  referenceEventSeriesId: zod.string().nullish(),
  startTimingType: zod.string().nullish(),
  isActive: zod.boolean().optional(),
  orderIndex: zod.number().optional(),
  initialAmount: zod.number().nullish(),
  annualChange: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  inflationAdjusted: zod.boolean().optional(),
  userPercentage: zod.number().nullish(),
  isSocialSecurity: zod.boolean().optional(),
  isDiscretionary: zod.boolean().optional(),
  assetAllocation: zod.record(zod.string(), zod.number()).nullish(),
  isGlidePath: zod.boolean().optional(),
  initialAllocation: zod.record(zod.string(), zod.number()).nullish(),
  finalAllocation: zod.record(zod.string(), zod.number()).nullish(),
  maximumCash: zod.number().nullish(),
  targetTaxStatus: zod.enum(['NonRetirement', 'PreTaxRetirement', 'AfterTaxRetirement']).optional(),
  createdAt: zod.string().datetime({}).optional(),
  updatedAt: zod.string().datetime({}).optional()
});

export const getApiScenariosScenarioIdRebalanceEventsParams = zod.object({
  scenarioId: zod.string()
});

export const getApiScenariosScenarioIdRebalanceEventsResponseItem = zod.object({
  id: zod.string().nullable(),
  scenarioId: zod.string().nullable(),
  name: zod.string().nullable(),
  description: zod.string().nullish(),
  eventType: zod.enum(['Income', 'Expense', 'Invest', 'Rebalance']).optional(),
  startYear: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  duration: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  referenceEventSeriesId: zod.string().nullish(),
  startTimingType: zod.string().nullish(),
  isActive: zod.boolean().optional(),
  orderIndex: zod.number().optional(),
  initialAmount: zod.number().nullish(),
  annualChange: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  inflationAdjusted: zod.boolean().optional(),
  userPercentage: zod.number().nullish(),
  isSocialSecurity: zod.boolean().optional(),
  isDiscretionary: zod.boolean().optional(),
  assetAllocation: zod.record(zod.string(), zod.number()).nullish(),
  isGlidePath: zod.boolean().optional(),
  initialAllocation: zod.record(zod.string(), zod.number()).nullish(),
  finalAllocation: zod.record(zod.string(), zod.number()).nullish(),
  maximumCash: zod.number().nullish(),
  targetTaxStatus: zod.enum(['NonRetirement', 'PreTaxRetirement', 'AfterTaxRetirement']).optional(),
  createdAt: zod.string().datetime({}).optional(),
  updatedAt: zod.string().datetime({}).optional()
});
export const getApiScenariosScenarioIdRebalanceEventsResponse = zod.array(
  getApiScenariosScenarioIdRebalanceEventsResponseItem
);

export const getApiScenariosScenarioIdRebalanceEventsIdParams = zod.object({
  scenarioId: zod.string(),
  id: zod.string()
});

export const getApiScenariosScenarioIdRebalanceEventsIdResponse = zod.object({
  id: zod.string().nullable(),
  scenarioId: zod.string().nullable(),
  name: zod.string().nullable(),
  description: zod.string().nullish(),
  eventType: zod.enum(['Income', 'Expense', 'Invest', 'Rebalance']).optional(),
  startYear: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  duration: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  referenceEventSeriesId: zod.string().nullish(),
  startTimingType: zod.string().nullish(),
  isActive: zod.boolean().optional(),
  orderIndex: zod.number().optional(),
  initialAmount: zod.number().nullish(),
  annualChange: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  inflationAdjusted: zod.boolean().optional(),
  userPercentage: zod.number().nullish(),
  isSocialSecurity: zod.boolean().optional(),
  isDiscretionary: zod.boolean().optional(),
  assetAllocation: zod.record(zod.string(), zod.number()).nullish(),
  isGlidePath: zod.boolean().optional(),
  initialAllocation: zod.record(zod.string(), zod.number()).nullish(),
  finalAllocation: zod.record(zod.string(), zod.number()).nullish(),
  maximumCash: zod.number().nullish(),
  targetTaxStatus: zod.enum(['NonRetirement', 'PreTaxRetirement', 'AfterTaxRetirement']).optional(),
  createdAt: zod.string().datetime({}).optional(),
  updatedAt: zod.string().datetime({}).optional()
});

export const putApiScenariosScenarioIdRebalanceEventsIdParams = zod.object({
  scenarioId: zod.string(),
  id: zod.string()
});

export const putApiScenariosScenarioIdRebalanceEventsIdBodyNameMax = 255;
export const putApiScenariosScenarioIdRebalanceEventsIdBodyDescriptionMax = 1000;
export const putApiScenariosScenarioIdRebalanceEventsIdBodyStartTimingTypeMax = 50;

export const putApiScenariosScenarioIdRebalanceEventsIdBody = zod.object({
  name: zod.string().min(1).max(putApiScenariosScenarioIdRebalanceEventsIdBodyNameMax),
  description: zod
    .string()
    .max(putApiScenariosScenarioIdRebalanceEventsIdBodyDescriptionMax)
    .nullish(),
  startYear: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  duration: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  referenceEventSeriesId: zod.string().nullish(),
  startTimingType: zod
    .string()
    .max(putApiScenariosScenarioIdRebalanceEventsIdBodyStartTimingTypeMax)
    .nullish(),
  isActive: zod.boolean().optional(),
  orderIndex: zod.number().optional(),
  assetAllocation: zod.record(zod.string(), zod.number()),
  isGlidePath: zod.boolean().optional(),
  initialAllocation: zod.record(zod.string(), zod.number()).nullish(),
  finalAllocation: zod.record(zod.string(), zod.number()).nullish(),
  targetTaxStatus: zod.enum(['NonRetirement', 'PreTaxRetirement', 'AfterTaxRetirement'])
});

export const putApiScenariosScenarioIdRebalanceEventsIdResponse = zod.object({
  id: zod.string().nullable(),
  scenarioId: zod.string().nullable(),
  name: zod.string().nullable(),
  description: zod.string().nullish(),
  eventType: zod.enum(['Income', 'Expense', 'Invest', 'Rebalance']).optional(),
  startYear: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  duration: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  referenceEventSeriesId: zod.string().nullish(),
  startTimingType: zod.string().nullish(),
  isActive: zod.boolean().optional(),
  orderIndex: zod.number().optional(),
  initialAmount: zod.number().nullish(),
  annualChange: zod
    .object({
      type: zod.string().nullable(),
      value: zod.number().nullish(),
      mean: zod.number().nullish(),
      stdev: zod.number().nullish(),
      lower: zod.number().nullish(),
      upper: zod.number().nullish()
    })
    .optional(),
  inflationAdjusted: zod.boolean().optional(),
  userPercentage: zod.number().nullish(),
  isSocialSecurity: zod.boolean().optional(),
  isDiscretionary: zod.boolean().optional(),
  assetAllocation: zod.record(zod.string(), zod.number()).nullish(),
  isGlidePath: zod.boolean().optional(),
  initialAllocation: zod.record(zod.string(), zod.number()).nullish(),
  finalAllocation: zod.record(zod.string(), zod.number()).nullish(),
  maximumCash: zod.number().nullish(),
  targetTaxStatus: zod.enum(['NonRetirement', 'PreTaxRetirement', 'AfterTaxRetirement']).optional(),
  createdAt: zod.string().datetime({}).optional(),
  updatedAt: zod.string().datetime({}).optional()
});

export const deleteApiScenariosScenarioIdRebalanceEventsIdParams = zod.object({
  scenarioId: zod.string(),
  id: zod.string()
});
