/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Scenario Manager API
 * API for managing scenarios, strategies, and investments.
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreateRebalanceEventRequest,
  EventSeriesResponse
} from '../scenarioManagerAPI.schemas';

export const getRebalanceEvents = () => {
  const postApiScenariosScenarioIdRebalanceEvents = <TData = AxiosResponse<EventSeriesResponse>>(
    scenarioId: string,
    createRebalanceEventRequest: CreateRebalanceEventRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post(
      `http://localhost:5010/api/scenarios/${scenarioId}/rebalance-events`,
      createRebalanceEventRequest,
      options
    );
  };
  const getApiScenariosScenarioIdRebalanceEvents = <TData = AxiosResponse<EventSeriesResponse[]>>(
    scenarioId: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`http://localhost:5010/api/scenarios/${scenarioId}/rebalance-events`, options);
  };
  const getApiScenariosScenarioIdRebalanceEventsId = <TData = AxiosResponse<EventSeriesResponse>>(
    scenarioId: string,
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(
      `http://localhost:5010/api/scenarios/${scenarioId}/rebalance-events/${id}`,
      options
    );
  };
  const putApiScenariosScenarioIdRebalanceEventsId = <TData = AxiosResponse<EventSeriesResponse>>(
    scenarioId: string,
    id: string,
    createRebalanceEventRequest: CreateRebalanceEventRequest,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.put(
      `http://localhost:5010/api/scenarios/${scenarioId}/rebalance-events/${id}`,
      createRebalanceEventRequest,
      options
    );
  };
  const deleteApiScenariosScenarioIdRebalanceEventsId = <TData = AxiosResponse<null>>(
    scenarioId: string,
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios
      .delete(`http://localhost:5010/api/scenarios/${scenarioId}/rebalance-events/${id}`, options)
      .then((res) => {
        if (res.data === '') res.data = null;
        return res as TData;
      });
  };
  return {
    postApiScenariosScenarioIdRebalanceEvents,
    getApiScenariosScenarioIdRebalanceEvents,
    getApiScenariosScenarioIdRebalanceEventsId,
    putApiScenariosScenarioIdRebalanceEventsId,
    deleteApiScenariosScenarioIdRebalanceEventsId
  };
};
export type PostApiScenariosScenarioIdRebalanceEventsResult = AxiosResponse<EventSeriesResponse>;
export type GetApiScenariosScenarioIdRebalanceEventsResult = AxiosResponse<EventSeriesResponse[]>;
export type GetApiScenariosScenarioIdRebalanceEventsIdResult = AxiosResponse<EventSeriesResponse>;
export type PutApiScenariosScenarioIdRebalanceEventsIdResult = AxiosResponse<EventSeriesResponse>;
export type DeleteApiScenariosScenarioIdRebalanceEventsIdResult = AxiosResponse<null>;
