/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ScenarioManager.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import { createMutation, createQuery } from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreateStrategyRequest,
  StrategyResponse
} from '../scenarioManagerApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

export const postApiScenariosScenarioIdStrategies = (
  scenarioId: string,
  createStrategyRequest: CreateStrategyRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<StrategyResponse>> => {
  return axios.post(`/api/scenarios/${scenarioId}/strategies`, createStrategyRequest, options);
};

export const getPostApiScenariosScenarioIdStrategiesMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof postApiScenariosScenarioIdStrategies>>,
    TError,
    { scenarioId: string; data: CreateStrategyRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdStrategies>>,
  TError,
  { scenarioId: string; data: CreateStrategyRequest },
  TContext
> => {
  const mutationKey = ['postApiScenariosScenarioIdStrategies'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiScenariosScenarioIdStrategies>>,
    { scenarioId: string; data: CreateStrategyRequest }
  > = (props) => {
    const { scenarioId, data } = props ?? {};

    return postApiScenariosScenarioIdStrategies(scenarioId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiScenariosScenarioIdStrategiesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdStrategies>>
>;
export type PostApiScenariosScenarioIdStrategiesMutationBody = CreateStrategyRequest;
export type PostApiScenariosScenarioIdStrategiesMutationError = AxiosError<unknown>;

export const createPostApiScenariosScenarioIdStrategies = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof postApiScenariosScenarioIdStrategies>>,
      TError,
      { scenarioId: string; data: CreateStrategyRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof postApiScenariosScenarioIdStrategies>>,
  TError,
  { scenarioId: string; data: CreateStrategyRequest },
  TContext
> => {
  const mutationOptions = getPostApiScenariosScenarioIdStrategiesMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
export const getApiScenariosScenarioIdStrategies = (
  scenarioId: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<StrategyResponse[]>> => {
  return axios.get(`/api/scenarios/${scenarioId}/strategies`, options);
};

export const getGetApiScenariosScenarioIdStrategiesQueryKey = (scenarioId?: string) => {
  return [`/api/scenarios/${scenarioId}/strategies`] as const;
};

export const getGetApiScenariosScenarioIdStrategiesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategies>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategies>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiScenariosScenarioIdStrategiesQueryKey(scenarioId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategies>>> = ({
    signal
  }) => getApiScenariosScenarioIdStrategies(scenarioId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!scenarioId,
    useQuery: true,
    staleTime: 300000,
    ...queryOptions
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategies>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiScenariosScenarioIdStrategiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategies>>
>;
export type GetApiScenariosScenarioIdStrategiesQueryError = AxiosError<unknown>;

export function createGetApiScenariosScenarioIdStrategies<
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategies>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategies>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiScenariosScenarioIdStrategiesQueryOptions(scenarioId, options);

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiScenariosScenarioIdStrategiesId = (
  scenarioId: string,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<StrategyResponse>> => {
  return axios.get(`/api/scenarios/${scenarioId}/strategies/${id}`, options);
};

export const getGetApiScenariosScenarioIdStrategiesIdQueryKey = (
  scenarioId?: string,
  id?: string
) => {
  return [`/api/scenarios/${scenarioId}/strategies/${id}`] as const;
};

export const getGetApiScenariosScenarioIdStrategiesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategiesId>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  id: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategiesId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiScenariosScenarioIdStrategiesIdQueryKey(scenarioId, id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategiesId>>
  > = ({ signal }) =>
    getApiScenariosScenarioIdStrategiesId(scenarioId, id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(scenarioId && id),
    useQuery: true,
    staleTime: 300000,
    ...queryOptions
  } as CreateQueryOptions<
    Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategiesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiScenariosScenarioIdStrategiesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategiesId>>
>;
export type GetApiScenariosScenarioIdStrategiesIdQueryError = AxiosError<unknown>;

export function createGetApiScenariosScenarioIdStrategiesId<
  TData = Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategiesId>>,
  TError = AxiosError<unknown>
>(
  scenarioId: string,
  id: string,
  options?: {
    query?: Partial<
      CreateQueryOptions<
        Awaited<ReturnType<typeof getApiScenariosScenarioIdStrategiesId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetApiScenariosScenarioIdStrategiesIdQueryOptions(
    scenarioId,
    id,
    options
  );

  const query = createQuery(queryOptions, queryClient) as CreateQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiScenariosScenarioIdStrategiesId = (
  scenarioId: string,
  id: string,
  createStrategyRequest: CreateStrategyRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<StrategyResponse>> => {
  return axios.put(`/api/scenarios/${scenarioId}/strategies/${id}`, createStrategyRequest, options);
};

export const getPutApiScenariosScenarioIdStrategiesIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof putApiScenariosScenarioIdStrategiesId>>,
    TError,
    { scenarioId: string; id: string; data: CreateStrategyRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdStrategiesId>>,
  TError,
  { scenarioId: string; id: string; data: CreateStrategyRequest },
  TContext
> => {
  const mutationKey = ['putApiScenariosScenarioIdStrategiesId'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiScenariosScenarioIdStrategiesId>>,
    { scenarioId: string; id: string; data: CreateStrategyRequest }
  > = (props) => {
    const { scenarioId, id, data } = props ?? {};

    return putApiScenariosScenarioIdStrategiesId(scenarioId, id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiScenariosScenarioIdStrategiesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdStrategiesId>>
>;
export type PutApiScenariosScenarioIdStrategiesIdMutationBody = CreateStrategyRequest;
export type PutApiScenariosScenarioIdStrategiesIdMutationError = AxiosError<unknown>;

export const createPutApiScenariosScenarioIdStrategiesId = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof putApiScenariosScenarioIdStrategiesId>>,
      TError,
      { scenarioId: string; id: string; data: CreateStrategyRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof putApiScenariosScenarioIdStrategiesId>>,
  TError,
  { scenarioId: string; id: string; data: CreateStrategyRequest },
  TContext
> => {
  const mutationOptions = getPutApiScenariosScenarioIdStrategiesIdMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
export const deleteApiScenariosScenarioIdStrategiesId = (
  scenarioId: string,
  id: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<null>> => {
  return axios.delete(`/api/scenarios/${scenarioId}/strategies/${id}`, options);
};

export const getDeleteApiScenariosScenarioIdStrategiesIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof deleteApiScenariosScenarioIdStrategiesId>>,
    TError,
    { scenarioId: string; id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): CreateMutationOptions<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdStrategiesId>>,
  TError,
  { scenarioId: string; id: string },
  TContext
> => {
  const mutationKey = ['deleteApiScenariosScenarioIdStrategiesId'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiScenariosScenarioIdStrategiesId>>,
    { scenarioId: string; id: string }
  > = (props) => {
    const { scenarioId, id } = props ?? {};

    return deleteApiScenariosScenarioIdStrategiesId(scenarioId, id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiScenariosScenarioIdStrategiesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdStrategiesId>>
>;

export type DeleteApiScenariosScenarioIdStrategiesIdMutationError = AxiosError<unknown>;

export const createDeleteApiScenariosScenarioIdStrategiesId = <
  TError = AxiosError<unknown>,
  TContext = unknown
>(
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof deleteApiScenariosScenarioIdStrategiesId>>,
      TError,
      { scenarioId: string; id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): CreateMutationResult<
  Awaited<ReturnType<typeof deleteApiScenariosScenarioIdStrategiesId>>,
  TError,
  { scenarioId: string; id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiScenariosScenarioIdStrategiesIdMutationOptions(options);

  return createMutation(mutationOptions, queryClient);
};
